steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-t', 'gcr.io/mlopsproject-374511/mlops-final', '.']
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/mlopsproject-374511/mlops-final']

steps:
   - name: 'gcr.io/cloud-builders/docker'
     args: ['build', '-t', 'gcr.io/mlopsproject-374511/inference', '-f', 'inference.dockerfile', '.']
   - name: 'gcr.io/cloud-builders/docker'
     args: ['push', 'gcr.io/mlopsproject-374511/inference']
